---
name: ğŸ¥‡ First Interaction

on:
  pull_request:
    types:
      - opened
  issues:
    types:
      - opened

permissions:
  issues: write
  pull-requests: write

jobs:
  first-interaction:
    name: ğŸŒ“ Greetings Earthling
    runs-on: ubuntu-latest
    steps:
      - name: ğŸƒğŸ¼ Run First Interaction
        uses: actions/first-interaction@1c4688942c71f71d4f5502a26ea67c331730fa4d
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          issue_message: |
            Thanks for opening this issue! We appreciate your contribution.
          pr_message: |
            Thanks for your first pull request! We appreciate your contribution.
