---
name: ğŸ¤– Pull Request Labeler

on: # zizmorlinter:disable dangerous-triggers
  - pull_request_target

permissions:
  contents: read

jobs:
  label:
    name: ğŸ·ï¸ Auto-Label Pull Request
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ·ï¸ Apply Labels using Labeler
        uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          sync-labels: true
